services:
  - type: web
    name: gpt-trainer-auth
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ADMIN_API_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./gpttrainer.db
    plan: free